### ISSUE TITLE
Is this library still being updated?

### ISSUE THREAD

**Issue by paulakg4** [mrichardson23/mrBBIO#16]
Hi I noticed you have issues open to add PWM support and other things. Are these updates still in the works or is this project pretty much dead?

I prefer it over PyBBIO because of the cleanup, but I know PyBBIO is still active and am wondering if I should just adapt PyBBIO.

**Comment by mrichardson23** [comment]
No, it's not dead at all. In fact, I've pushed changes to it 21 days ago and I'm still working on it.
